### ISSUE TITLE
TST: use yield for pytest taredown

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#112]
Just as a suggestion would it be possible to use yield in `conftest`? It seems like it may be cleaner without injecting any horrible problems into the code.

**Comment by tacaswell** [comment]
sure.  Is there a down side to what we are doing now (other than 'less clean')?

**Comment by CJ-Wright** [comment]
I am writing some ugly stuff for testing export with a read only filestore

**Comment by tacaswell** [comment]
if it makes your life better, than go for it!

If it is out of a sense of 'right-ness that works just as well', don't bother.

**Comment by CJ-Wright** [comment]
I was hoping to make a nice generalization of the build fixtures so that we could get back read only filestore backed databrokers.
