### ISSUE TITLE
Set up Archiver Appliance in Travis so we can test Archiver integration

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#132]
We keep accidentally breaking it. Can you tackle this, @arkilic?

**Comment by ambarb** [comment]
@arkilic , @danielballan  can you guys provide an estimation of delivery?  We need to be able to surf the archiver to look from problems and plot against the data (which is a single point in db, despite being one or two hours of data collection).

**Comment by danielballan** [comment]
Sometime between tonight and two weeks from tonight.

**Comment by danielballan** [comment]
Surfacing a suggestion I've mentioned in conversation and on Slack: https://github.com/kevin1024/vcrpy would be a good way to test this on Travis-CI without actually having to install the Archiver on Travis-CI. For those who don't already know, VCR works like this:

1. Stand up a working server _locally_ once. In our case, we could use the actual Archiver running at NSLS-II.
2. Run the tests. For every request that occurs during the test, VCR captures the client's request and the corresponding response from the server. It records this information in JSON files that are intended to be added to version control.
3. Tear down the server (or switch to a machine that can't see the server).
4. Run the tests again. VCR magically mocks the server's response to each client request.

Thus, there is no need to get the server working on Travis-CI. Of course, if a test issues a request that VCR has not seen before, VCR blows up and the test fails, but you are free to _refactor_ the tests without re-generating the VCR files.

**Comment by mrakitin** [comment]
I love that!

**Comment by danielballan** [comment]
This is done.
