### ISSUE TITLE
Question: Can I always expect a `filled` key in events?

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#146]
I'd like to know if I can build code on `filled`.

**Comment by danielballan** [comment]
Presently, Event documents from the databroker always includes a `filled` key but Events from the RunEngine never do. In the spirit of making databroker and RunEngine more identical, I think we should add a `filled` key to RunEngine Events. This would allow us to clean up some callback code that presently relies on heuristics to figure out if an Event has an image in it.

**Comment by danielballan** [comment]
Data at rest never has a filled key; data in flight always does.
