### ISSUE TITLE
Make Broker and all components pickle-able.

### ISSUE THREAD

**Issue by jrmlhermitte** [bluesky/databroker#151]
I think a new version of databroker now supplies the databroker instance in the returned headers (from say `hdr = db[-1]` now has a `hdr.db`). Is that correct?

If yes, is there a way to get headers that don't have `databroker` instances? It doesn't pickle well in a distributed environment. (Or anything without references to open files/sockets etc?)

I would suggest maybe some object, like `RelocatableHeader` or something, which instead of db itself, is just the conf dict necessary to rebuild the database. What do you think? Just throwing this out there.

If I'm misunderstanding anything, please correct me, and thanks for the support as always, it's much appreciated.

thanks!

julien

PS: I should mention we also want some way of being able to identify they're headers, so `dict(myheader)` is not sufficient, but 
```python
class HeaderDict(dict):
    def __init__(self, input):
        super(HeaderDict, self).__init__(input)
```
would be for `isinstance(myheader, SomeClassNotDict)`.

**Comment by danielballan** [comment]
That's correct. Have you tried `relocatable_header = dict(header)`?

**Comment by tacaswell** [comment]
It is better to make the various broker parts pickable

**Comment by ordirules** [comment]
sorry for delay @danielballan. Yes, that's what I'm currently doing, but then it's just a dictionary instance. I did as shown above using some new class `HeaderDict`, which also contains arbitrary methods that can be pickled. My concern was that the object contains stuff that can't be pickled (which I'm guessing in this case is an open socket to mongodb?).

thanks @tacaswell I +1 your suggestion, but am also working around it just fine (in the event you don't want to implement). Also thanks @arkilic for explaining more details about the structure of the headers.

**Comment by danielballan** [comment]
I imagine we can pickle the connection info and recreate the connection in `__setstate__()`. In general Python encourages us to make *all* custom classes pickleable. We should have done this from the start.

**Comment by danielballan** [comment]
This can made a high priority once the giant merge in #145 is done. We can do them all in one PR.
