### ISSUE TITLE
A filestore by any other name would smell as sweet?

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#187]
It's exhausting to explain that "filestore" does not store files. I like "asset_registry" (better than "resource_registry", the current name of the module in databroker). But I'm questioning whether we want to go through the painful API break of changing not only the module name but also the object names everywhere. On balance, I'm ambivalent.

Where do others stand on this?

**Comment by stuartcampbell** [comment]
Any chance we would start a confusion with other projects that do similar things with similar names ?  e.g. https://girder.readthedocs.io/en/latest/user-guide.html#assetstores ? 😁

**Comment by stuartcampbell** [comment]
But I do like the "asset" based name

**Comment by danielballan** [comment]
Yeah, "asset" is a standard term for "heavy binary dependency" in the web world too. It seems like a good choice. Is "assert registry" (an accurate description of what this does) sufficiently different from "asset store"?

**Comment by danielballan** [comment]
We could support the old names with warnings for awhile, but this would still be pain. It would probably mean changing a little ophyd API (again with warnings for awhile) from `fs` to `ar` for "asset registry" or whatever name we choose.

I'd be interested to know if @ordirules, @CJ-Wright, and any others think increased clarity is worth this pain. I'm torn.

**Comment by CJ-Wright** [comment]
I'm so deep into the existing system at this point that I don't mind the name. However, some people run into issues with the "file" in the name, since it might be associated with a "file based workflow" connotation which we are actively not pursuing.

**Comment by jrmlhermitte** [comment]
I'm not sure. In linux, file can mean from data on disk to something virtualized, and people have been fine with that. I feel like `databroker` is about the same thing. I'd be inclined to say it's not worth the pain.
However, to add to your data points, I'm fine with the change if you decide to do it, and agree it's clearer (I like `asset` as well). I guess the question will come down to how many other people you have to also make sure are kept happy? Has bluesky been deployed outside NSLS-II (yet)? If you're feeling doubts and noticing confusion between scientists now then maybe it's definitely worth the switch before it (potentially) gets deployed elsewhere?

**Comment by danielballan** [comment]
Bluesky and ophyd are widely enough deployed that I wouldn't make a change like this on them. But databroker and its dependencies are still in a more primordial phase, and they are not deployed in production outside NSLS-II to my knowledge. Databroker is intentionally still not on PyPI.

**Comment by danielballan** [comment]
Not yet sure whether to pull the trigger on this, but in the meantime more naming ideas... what about just `Assets`? It's all scoped under the databroker package now, so it doesn't need a particularly unique name, just a descriptive one. It seems like we all like "asset" but are less excited about "asset registry," which is a mouthful anyway.

**Comment by danielballan** [comment]
We're going with:

* FileStore -> Assets
* resource document -> asset
* datum document -> ???

**Comment by danielballan** [comment]
Disregard my previous comment. I misunderstood Tom's feelings on this subject, and given our short manpower it seems unlikely we'll undertake internal renaming without his enthusiastic support.
