### ISSUE TITLE
Revisit our choice to use Doct and document our reasoning

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#191]
@tacaswell and I last revisited this, by phone, about six months ago. One can make a case for returning plain dicts, as RunEngine does, but ultimately we decided it wasn't a strong enough case. The original motivations for creating doct were immutability (of which it does a less-than-perfect job) and adding getattr-based access as a synonym for getitem-based access, which is convenient but has downsides.

If we decide to stick with doct (which I suspect we will) then we should document our reasoning somewhere.

**Comment by danielballan** [comment]
We are strongly leaning toward dropping doct. One original reason for needing it becomes moot when documents have uids instead of references to other documents. This change would also break dot access (but tab complete would still work on getitem access). Users handle documents interactively much less than we expected.

Concerns, anyone?

**Comment by CJ-Wright** [comment]
I'm just happy that this means that all the documents will be consistent :smile:

**Comment by danielballan** [comment]
Documenting an in-person design discussion with @tacaswell:

Goals:
* Create a path to fully removing `doct` and just representing documents as plain dictionary objects.
* Do not break dot access in this release. That is, continue to support `event.data` as a synonym for `event['data']`... at least for now.

Proposed path:

1. Remove the special `_name` key from doct, so that the `Doct` object becomes nothing more than a dict subclass that supports `__getattr__` (dot access) as a synonym for `__getitem__` (square bracket lookup). Removing `_name` is an API change, but in practice it is not expected to break any user code.
2. Make all internal Broker components (mds and fs variants) represent documents as plain dict objects internally, thus saving on performance.
3. Wherever Broker returns document to the user, as in `header.stream()`, pass the document through a new `Broker.prepare_hook(name, doc)` method on the way out. By default, `prepare_hook` will convert the dict into a `Doct`, thus maintaining API continuity for the user. But the user can change `prepare_hook` to, for example, make a deep copy instead, and return a plain dict.
4. Make `Doct.__getattr__` warn that dot access may be removed in a future release. See how much push-back we get about removing dot access.
5. If removing doct entirely (and breaking dot access) still feel like a good idea, change the default behavior of `prepare_hook` in a future release.

**Comment by danielballan** [comment]
I followed this path in #219. Instead of changing `doct` itself, I wrapped it in a subclass `DeprecatedDoct`.  When you try to use dot access to access items (as in `event.data`), it warns we _might_ remove that in the future and that that should use `event['data']` instead.

Users annoyed by these warnings can get the old behavior back like so.

```python
from databroker.broker import wrap_in_doct
db.prepare_hook = wrap_in_doct
```
