### ISSUE TITLE
Stash filestore token even when filled

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#196]
I've ran into an issue with filtering the data.
Generally we want to filter on the actual data, which requires the events to be filled. After filtering it would be nice to have the option of passing the data into the databroker (for instance if your filtering took a long time to execute). However, the data didn't change (the image is still the same) only how we have represented it in MDS. In this situation it might be nice to have the filestore tokens handy, as we could bypass saving the data onto disk and just hand MDS the existing FS token. With this in mind would it be possible to stash the filestore token somewhere inside the event data even after filling?

**Comment by CJ-Wright** [comment]
As part of this we may want something to address a filestore, that way if you have multiple databrokers on a system we know which one to look at when we want to get the data back, see #194

**Comment by CJ-Wright** [comment]
@tacaswell @arkilic

**Comment by tacaswell** [comment]
I am mostly :-1: on this as it surfaces more details about how the data is stored on the back than I really want to have surfaced, however this is a compelling use case.

In the case of filtering, it may be better to write down event uids and lobby for the 'get a single event' API to be revived or to write down a binary mask + header uid.

The `'external'` string in the descriptor is intended to identify which filestore the data is actually stored in, but there is nothing built out around that yet.

**Comment by CJ-Wright** [comment]
I'm not a fan of having a double retrieval for this, especially as there isn't a nice API for the retrieval of events within events or events from a binary mask + header uid like there is for getting filestore data. I don't know about "[surfacing] more details about how the data is stored" we already hand back filestore tokens from both the RunEngine and `hdr.stream(fill=False)`. I guess we could always monkey patch the token as a private attribute onto the resulting object on its way out of filestore :smiling_imp:

**Comment by tacaswell** [comment]
What is "events within events" ?

While the uids are exposed, they are mostly exposed as place-holder tokens that should be opaque to the users. 

If we do this, I think the correct place to stash this information is in the filled dictionary.

**Comment by CJ-Wright** [comment]
Maybe I should try to give more context. The output of my filtering is a new stream in the event model, with a new `start`, `descriptor`, `event`(s), and `stop`.
My interpretation of what you wrote was that I could stuff `event_uids` into my new events and then unpack them later via the `get_single_event` API.

I am ok with putting this in filled.

**Comment by CJ-Wright** [comment]
Do you want a PR to add the tokens to filled?

**Comment by danielballan** [comment]
Closed by #200
