### ISSUE TITLE
Should __getitem__ return Result?

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#197]
Should `__getitem__` return a `Result` instance? One could imagine `db[-100:]` and not wanting everything there at once.

**Comment by danielballan** [comment]
One important difference between an arbitrary query and a getitem one is that you always know exactly how many Headers you'll get back from a getitem one. You'll never be in a situation where you accidentally get a huge result set. So, you can always do:

```python
results = (db[-i] for i in range(-100, -1))
```

**Comment by CJ-Wright** [comment]
Fair enough
