### ISSUE TITLE
Slicing Indexes

### ISSUE THREAD

**Issue by stuwilkins** [bluesky/databroker#198]
We have run up against an issue with the lazy loading of images with `filestore`. At CSX we usualy take datasets which are of a large number of images per point. As we index our data as :
```
[(point), (image), (y), (X)]
```
We lazy load on point. i.e. the generator goes through and returns `[(image), (y), (x)]`.

The problem with this, is this breaks if you have `(image)` >> `(point)`.

How do we lazy load 2 deep?

**Comment by tacaswell** [comment]
You should be getting back lazy objects from your handlers already.

**Comment by stuwilkins** [comment]
Yes... we are getting objects back, but I suspect something in the HDF5 layer, it needs more debugging on my part before repoening this.
