### ISSUE TITLE
make client/server tests more reliable

### ISSUE THREAD

**Issue by tacaswell** [bluesky/databroker#221]
The databroker tests with the client randomly fail on starting the server

https://travis-ci.org/NSLS-II/databroker/jobs/263097538

We should either shorten the existing timeout and then re-try starting the server or watch the stdout/return from the process to know if it has started or failed.

**Comment by danielballan** [comment]
As written, the server tries to bind to a specific port. I would bet that the OS is not cleaning up old sockets fast enough, and therefore the server startup is dying on failure to bind to the port. Could we use random ports (provided by the OS) in the tests?

**Comment by tacaswell** [comment]
The fixture already uses a random port in one place (https://github.com/NSLS-II/databroker/blob/master/databroker/tests/utils.py#L136) but not all!
