### ISSUE TITLE
BUG: `db.fill_event` broken?

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#239]
Relevant output
https://travis-ci.org/xpdAcq/xpdAn/jobs/263914210#L1249

`db.fill_event` called [here](https://github.com/xpdAcq/xpdAn/blob/aa4b7f42d8b39bcafccff330a95206dc6e6387b4/xpdan/callbacks_core.py#L159)

**Comment by tacaswell** [comment]
what version of databroker are you using?

**Comment by tacaswell** [comment]
And can you please provide a minimal example?

**Comment by CJ-Wright** [comment]
databroker was pip installed from master

**Comment by CJ-Wright** [comment]
It seems that this was a problem between databroker and metadatastore (I've updated our code to use the databroker test utilities).
