### ISSUE TITLE
file resources broken?

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#240]
It seems that a pip install from master does not capture the schemas?
https://travis-ci.org/CJ-Wright/xpdAn/jobs/263936602#L1531

`pip install https://github.com/NSLS-II/databroker/zipball/master#egg=databroker`
```python
from databroker.tests.conftest import db
```
yields error
`FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/mc/envs/testenv/lib/python3.5/site-packages/databroker/assets/schemas/AD_HDF5_resource.json'`

**Comment by danielballan** [comment]
Cannot reproduce:

```
>>> from databroker.tests.conftest import db
>>> import databroker
>>> databroker.__version__
'0.8.4+2262.g84d7e2e6'
```

Nonetheless we should probably follow up on #231 we a refactor that uses `pkg_resources.resource_filename`.

**Comment by CJ-Wright** [comment]
How did you install the databroker?

**Comment by CJ-Wright** [comment]
Sorry wrong test code
try this:
```python
>>> from databroker.assets.base_registry import BaseREgistryRO
```
I got 
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/christopher/mc/envs/test_pyfai/lib/python3.6/site-packages/databroker/assets/base_registry.py", line 26, in <module>
    class BaseRegistryRO(object):
  File "/home/christopher/mc/envs/test_pyfai/lib/python3.6/site-packages/databroker/assets/base_registry.py", line 82, in BaseRegistryRO
    resource_name), 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/home/christopher/mc/envs/test_pyfai/lib/python3.6/site-packages/databroker/assets/schemas/AD_HDF5_resource.json'
```
On my local pip install.

**Comment by danielballan** [comment]
I see. A installation via `python setup.py develop` works even if the pkg_resources haven't been configured correctly. One must use `pip install .` to reproduce locally.

See #241 for fix. Thanks for taking the time for the back-and-forth here.

**Comment by CJ-Wright** [comment]
Thank you! Sorry that I didn't have a breaking example the first go round (I have also had problems with `pkg_resources`).
