### ISSUE TITLE
Check in on register_builtin_handlers

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#248]
Make sure register_builtin_handlers() still works somehow (or devise something to replace it) and document that somewhere.

**Comment by stuwilkins** [comment]
HI @danielballan I checked and master "out of the box" does not register handlers. Take a look at:

http://nbviewer.jupyter.org/gist/stuwilkins/aacc922f0811c8928dfba25dd1812c57

vs.

http://nbviewer.jupyter.org/gist/8e4dff8b96717a856191f6bce2c5c6eb

It appears that there is no hook when you now do Broker.named to register the handlers but it is only then when you have the fs object.

**Comment by danielballan** [comment]
Solution in https://github.com/NSLS-II/databroker/pull/236/commits/0c833094dfb7866ab1840e8f4e4d815fe38a4b23

Creating a Broker via any method (init, from_config, named) auto-registers the built-in handlers until you pass in `auto_register=False`, which is an optional argument for all of those methods.

**Comment by danielballan** [comment]
Closed by #236
