### ISSUE TITLE
DOC: stub documentation?

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#255]
This doesn't seem complete
https://github.com/NSLS-II/databroker/blob/5dd77e678a4048b04594b01f88e5f4209187ca43/databroker/assets/base_registry.py#L695

**Comment by danielballan** [comment]
Thanks for flagging this. Documentation of the user-facing components (Broker) is cleaned up for this release, but documentation of the internal components will be a bit messy I'm afraid. We'll revisit that before the next release.

**Comment by CJ-Wright** [comment]
Is there going to be a `Broker` based wrapper for this?
