### ISSUE TITLE
REL: add scripts as entry points

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#260]
Would it be possible/desirable to add the scripts as entry points so they can be run from the command line even after `python setup.py develop`?

**Comment by tacaswell** [comment]
What scripts do you expect to see?  The only two we have are `fs_rename` which you should not be using and `start_md_server` which stands up a tornado server infront of your mongo.

This should already be the case (this is how we were starting the server for the client tests before we changed travis to do a normal install).

**Comment by CJ-Wright** [comment]
For some reason my system doesn't see those scripts when running tests, causing all the client tests to fail.

**Comment by danielballan** [comment]
I can't reproduce that locally. Can you elaborate on "when running tests"? Do you see them when not running tests? How do you run the tests?
