### ISSUE TITLE
Override Handler Registry

### ISSUE THREAD

**Issue by stuwilkins** [bluesky/databroker#264]
In the "new" API functions to get data there appears to be no way to override the default handlers. It is great to get data via the 

```python
dataset = db['5933c2']
data_gen = dataset.data('fccd_image')
data = list(data_gen)
```

But there is no way to override the handler to look at the data differently. `get_events`, has a method to override the handler but I thought these methods were now depreciated.

**Comment by stuartcampbell** [comment]
This should be documentated.

**Comment by CJ-Wright** [comment]
Does the context manager still work? (I don't have it at my fingertips right now though)

**Comment by danielballan** [comment]
@CJ-Wright Yes. That's the piece that's used internally, so it definitely works.
