### ISSUE TITLE
Known issue: the config search path does not include any Windows locations

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#277]
I think the correct path is something like

```python
os.path.join(os.environ['APPDATA'], 'databroker')
```

but we should try this on a Windows box.

**Comment by stuartcampbell** [comment]
Is the best way to test this to create a file in this directory and see if it shows up in the list of available config ?

**Comment by danielballan** [comment]
That sounds reasonable to me. We just need a Windows box.

**Comment by stuartcampbell** [comment]
I'll do it tonight when I go home... I only use Windoze for some games!  please don't judge me! :)

**Comment by CJ-Wright** [comment]
Is there any interest in testing this via a windows CI?

**Comment by stuartcampbell** [comment]
I think so, but I'm keen to just get this working and the release tagged.

I've created #279 for it.

**Comment by tacaswell** [comment]
Closed by #280
