### ISSUE TITLE
`/` in root/resource_path again

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#286]
We solved this issue before (I think) but its back. The main issue is that if `os.path.join` sees two paths starting with / it will ignore one of them.

**Comment by tacaswell** [comment]
This was intentional, fix your database.

**Comment by CJ-Wright** [comment]
Did a fix go out to XPD?

**Comment by tacaswell** [comment]
No, are you seeing this directly on their system or only on your exported databases?

**Comment by CJ-Wright** [comment]
Exported, although I had thought that at one point this extended back to XPD, although I could be wrong.
