### ISSUE TITLE
Rehabilitate `fill_event`

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#290]
It seems a bit odd to need to keep track of the descriptor for `fill_events` if I have a valid event with a valid descriptor uid. Also it would be handy to have a function which operates on a single event and fills it.

**Comment by danielballan** [comment]
It's reasonable to consider this. For anyone else reading along, we used to have a method `Broker.fill_event` that took in an Event document. Now we have deprecated `Broker.fill_event` in favor of `Broker.fill_events`, which takes in a list of Event documents and a list of all the Event Descriptor documents that they are linked to.

Let me document our reasoning as I remember it:

* Keeping track of the descriptor is something that most callbacks have to do anyway.
* If the user hands us an event with a descriptor uid but no descriptor, which "event source" should we search in to find it? Currently there is only the one "event source", but we plan to represent Archiver Appliance, Olog, and other data sources in this way, and recovering a descriptor could become tricky and slow.
* Maintaining both fill_events and fill_event seems confusing. Users who discover fill_event but not think to look for fill_events.

I don't mean to shut down discussion, just to document how we got to the decision of deprecating fill_event.

**Comment by tacaswell** [comment]
I am even on the fence of keeping `fill_events` as public API.  The main argument in favor of it is being lazy about filling events based on some other value in the event (the use case of "I only want some fraction of my events" can be handled by adding better slicing options to the the event retrieval methods).

The other relevant change here is that we stopped de-referencing the descriptor documents in the events so working on a single event was not too onerous. 

The counter argument is databroker _gave_ the user the descriptor, why should it look it up again?  If the user somehow loses the descriptor it is their responsibility to search for it again.

**Comment by CJ-Wright** [comment]
The use case I'm coming from is that I'd like to fill single events on the other side of a callback so that the pipeline is always working from live data rather than tokens. I could (and currently do) stash the descriptor, but it would be nice to not have to.

**Comment by tacaswell** [comment]
Why?

**Comment by tacaswell** [comment]
why do you have single event documents without an associated descriptor?

**Comment by CJ-Wright** [comment]
I am pulling the events from the RunEngine, and I'm not currently stashing their descriptors (although I think I changed that at one point). More generally, I would like to fill the events with a `map` node, however the `map` node may not have access to the descriptor information (since we are currently fairly adamant about computation being done on events, this may change in the near future though).

**Comment by tacaswell** [comment]
ok, so either your map node needs to do the search or you need to pass in the descriptors though.

I am :+1: on removing `fill_event` for 1.0.

**Comment by CJ-Wright** [comment]
just as an fyi, I wrote a dedicated node to do this so it can stash descriptors to it's heart's content. I was just hoping to have a more elegant solution (which `fill_event` kinda provided), but this is fine.
