### ISSUE TITLE
Should empty streams give error?

### ISSUE THREAD

**Issue by ambarb** [bluesky/databroker#304]
Scan 82996 has `sd.monitor = []`.  If the `stream_name` is not found, then should db give an error?

```python
In [10]: t=db.get_table(db[82996],stream_name='fccd_temp_monitor')

In [11]: t
Out[11]: 
Empty DataFrame
Columns: []
Index: []

In [12]: t=db.get_table(db[83007],stream_name='fccd_temp_monitor')

In [13]: t
Out[13]: 
                              time  fccd_temp
seq_num                                      
1       2017-09-10 16:05:25.902018    -59.979
2       2017-09-10 16:05:27.650428    -59.980

```

**Comment by danielballan** [comment]
It's a judgement call. By returning an empty DataFrame instead of raising an error, we allow usages like

```python
db.get_table[db[-100:], stream_name='fccd_temp_monitor')
```

where it's OK if not all of the last 100 runs had that stream.

**Comment by ambarb** [comment]
Good point.  But if a batch script tanks because one scan is missing the monitor stream, then atleast it would be immediately obvious.  However, I think it is worth a discussion among interested parties.


Dan Allan <notifications@github.com> wrote:


It's a judgement call. By returning an empty DataFrame instead of raising an error, we allow usages like

db.get_table[db[-100:], stream_name='fccd_temp_monitor')

where it's OK if not all of the last 100 runs had that stream.

**Comment by ambarb** [comment]
@danielballan Im thinking that your original line of thought is correct now.  It maximizes flexibility.  

However, maybe something that is a higher level function to get all of the monitor stream data would be appropriate to add a True or False for raising an exception if a monitor stream does not exist.

**Comment by danielballan** [comment]
Yeah, some optional flag like `not_empty`, False by default, could work.

**Comment by tacaswell** [comment]
I would rather put some helper methods on the `Header` object as `h.has_stream(...)` or make it the job of the consumer to raise of the return dataframe is empty.

**Comment by danielballan** [comment]
Do we want a special method `h.has_stream(name)`? I think `name in h.stream_names` is good enough.

**Comment by tacaswell** [comment]
`name in h.stream_names` is good enough

**Comment by stuartcampbell** [comment]
I think the `h.has_stream(name)` would be a nicety but not essential.  Maybe an issue for a new starter ?

**Comment by danielballan** [comment]
I wouldn't argue strongly against it, but I would point out that Python had a similar method -- `dict.has_key(name)` -- and [removed it in Python 3, recommending the `in` keyword instead](https://docs.python.org/3.1/whatsnew/3.0.html#builtins). Would you open an issue if you think this would be nice to have anyway, @stuartcampbell? I'll close this one.
