### ISSUE TITLE
StopIteration upon FileNotFoundError?

### ISSUE THREAD

**Issue by jrmlhermitte** [bluesky/databroker#313]
The following will yield a StopIteration after retrieving an event document, stopping the loop prematurely:
```python
hdrs = db(start_time="2017-10-20", stop_time="2017-10-21")
stream = db.restream(hdrs)
for nds in stream:
    # do something
```

What happens is that I encounter a `FileNotFoundError`. If anything is raised in a generator, a `StopIteration` follows its next call. Should there perhaps be a more gentle way to do this? Perhaps instead just ignoring the rest of this stream and issuing a stop document?

Or is there a more recommended way to do this? The problem I'm having here is that the resource is trying to load a file that doesn't exist, causing my stream to end prematurely. `try` and `except` won't work in this case (or at least I don't see a way)

PS: I think the  line involved is close to [here](https://github.com/NSLS-II/databroker/blob/master/databroker/_core.py#L2013).

**Comment by jrmlhermitte** [comment]
we'll do this:
```python
    def stream_gen(hdrs):
        ''' Intercept FileNotFoundError from file handler.
            Issue a stop if some error is raised
        '''
        current_start = None

        for hdr in hdrs:
            skip = False
            gen = hdr.documents(fill=True)
            try:
                for nds in gen:
                    # skip events if determined to do so
                    if nds[0] == 'event' and skip==True:
                        continue
                    if nds[0] == 'start':
                        current_start = nds[1]['uid']
                    yield nds 
            except FileNotFoundError:
                skip=True
```

curious if that is recommended or not.

EDIT: removed `raise StopIteration`

**Comment by tacaswell** [comment]
The correct way to bail on a geerator early is via `return`  https://www.python.org/dev/peps/pep-0479/

**Comment by jrmlhermitte** [comment]
All I don't want is that one bad `start`->`stop` event stream to stop the whole event stream.

when a bad `event` comes through, I still do want the `stop` to go through (or a new `stop` pointing to the right `start`). The snippet above also allows `descriptor` to still go through. But probably that should be prohibited as well.

thanks, I'll remove `raise StopIteration`

**Comment by danielballan** [comment]
Could you use try/finally get the 'stop' document out before bailing with `return`?

**Comment by jrmlhermitte** [comment]
I see the confusion. This is my mistake, here is what I intended to do:
```python
    from uuid import uuid4
    def stream_gen(hdrs):
        ''' Intercept FileNotFoundError from file handler.
            Issue a stop if some error is raised
        '''
        current_start = None
        for hdr in hdrs:
            gen = hdr.documents(fill=True)
            try:
                for nds in gen:
                    if nds[0] == 'start':
                        current_start = nds[1]['uid']
                    yield nds
            except FileNotFoundError:
                # don't yield event, just give a stop
                yield ('stop', {'uid' : str(uuid4()),
                                'run_start': current_start})

```
sorry about that. Does this make sense now? (I am keeping previous code for understanding)

**Comment by danielballan** [comment]
There is analogous code in the RunEngine that we can borrow to address this. If a RunEngine encounters an Exception, it passes it to the plan to allow the plan an opportunity to swallow it before reraising it and killing operation. I think would need to do something similar involving `proc_gen` to enable outer layers like your to opt-in to ignore Exceptions.

I write this while sitting under two hockey fans on a crowded LIRR train car, so I'll have to postpone further investigation to a more serene moment in my life.
