### ISSUE TITLE
extend config to allow for root_map

### ISSUE THREAD

**Issue by jrmlhermitte** [bluesky/databroker#325]
currently, configuration allows for the setting of many parameters, including the file handlers.
It would be nice to have a feature that allows the setting of a global `root_map`

reference : http://nsls-ii.github.io/databroker/configuration.html

**Comment by jrmlhermitte** [comment]
@tacaswell @danielballan @mrakitin

**Comment by danielballan** [comment]
relevant to @CJ-Wright's interests as well -- I wonder if we can tempt him to hammer out a quick PR ;-)

**Comment by CJ-Wright** [comment]
I don't know if any of my PRs in recent history have been *quick*. I will not be able to get to it this week most likely, I'm doing a deep dive in SHED.

**Comment by jrmlhermitte** [comment]
closed by #332
