### ISSUE TITLE
Add filter overwrites existing filters

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/databroker#352]
Current behavior

```python
db.add_filter(experimenters='CJ')
db.add_filter(experimenters="Emil")
print(db.filters)
{'experimenters': 'Emil'}
```

Expected behavior
```python
db.add_filter(experimenters='CJ')
db.add_filter(experimenters="Emil")
print(db.filters)
{'experimenters': {'Emil', 'CJ'}}
```
Edit: typo

**Comment by CJ-Wright** [comment]
Attn: @sbillinge

**Comment by mrakitin** [comment]
Did you type `exprimenters` correctly in the second case?

**Comment by CJ-Wright** [comment]
Yes, sorry I'll edit

**Comment by mrakitin** [comment]
I see, thanks. I thought the original commands were run with this typo as well, that's why you may have had the missing elements.

**Comment by danielballan** [comment]
I'm not sure that's what you'll get. Do you think we can safely assume that the expected behavior is `$or`? I generally expect filtering to compose as `$and`. I'm open to making `add_filter` more magical, but I'd like to see a thorough exploration of the trade-offs.

**Comment by CJ-Wright** [comment]
`$and` is reasonable. We ran into this during a demo session with @sbillinge, so he might have some thoughts on the expected filtering.

**Comment by tacaswell** [comment]
There is an 'obvious' merge for this case (although, I'm not sure if you are trying to ask "show me all of the scans that 'CJ' or 'Emil' were involved in" or "show me only the scans where both 'CJ' and 'Emil' were involved") and it only gets worse for more complex queries.  I think to do the merging of filters _well_ is more complexity that we want to take on right now.

**Comment by danielballan** [comment]
Superseded by intake's progressive search functionality
