### ISSUE TITLE
ENH: add EGU key to pandas data table

### ISSUE THREAD

**Issue by ambarb** [bluesky/databroker#353]
`db[-1].table()[hdr.start.motors[0]]` returns the motor positions associated with the particular scan.

for `my_motor = db[-1].table()[hdr.start.motors[0]] `, `my_motor.xname` returns the name of the motor assciated with the data frame.  I am using this to auto label the x-axis instead of modifying code in verbatim.  However, I still have to change the unit label.  Since engineering units are captured in the descriptors, can we please add an EGU key for end-user's convenience?

**Comment by danielballan** [comment]
`db.v2.primary.read()` now includes fields from the Events and fields from the EventDescriptors, all together.
