### ISSUE TITLE
What should we do when we have bad descriptors?

### ISSUE THREAD

**Issue by jrmlhermitte** [bluesky/databroker#370]
Right now:

```py
# where hdr is a Header
events = hdr.events()
event = next(events)
```
will raise a key error if the descriptor doesn't contain matching keys.

The 'data' key of this event is:
```
dict_items([('eiger4m_single_image', '040f7d00-eee5-4f3f-bd12-db202749b386'), ('eiger4m_single_stats1_total', 0.0), ('eiger4m_single_stats2_total', 0.0), ('eiger4m_single_stats3_total', 0.0), ('eiger4m_single_stats4_total', 38250.0), ('eiger4m_single_stats5_total', 1075253663200414.0)])
```

the 'data_keys' entry (in the descriptor) is:
```
{'eiger4m_single_image': {'shape': [2070, 2167, 0], 'source': 'PV:XF:11IDB-ES{Det:Eig4M}', 'dtype': 'array', 'external': 'FILESTORE:', 'object_name': 'eiger4m_single'}}
```

Should we be gentler and have `next(events)` not choke but rather return `None` or `StopIteration` with a warning?

Note that this data is likely gone from a bluesky scan gone horribly wrong.

Note this was encountered by @elParcero while going through the chx database.

**Comment by tacaswell** [comment]
I think failing hard is the correct behavior.  "There is no data" is very different than "This data is inconsistent".

**Comment by danielballan** [comment]
Agreed.
