### ISSUE TITLE
Search through descriptors

### ISSUE THREAD

**Issue by jrmlhermitte** [bluesky/databroker#373]
Should we allow search functionality through descriptors?
The reason is that sometimes a user may acquire data that should be saved in a descriptor, not start document. However, since only starts are searchable, this might tempt users to move such configuration data into the start.
@chiahaoliu and @CJ-Wright  requested this.

**Comment by danielballan** [comment]
Currently, the right approach is to iterate through all possibly-interesting Headers and do the "search" in Python. This should scale fine in practice for the next year or so at XPD, @CJ-Wright @chiahaoliu, while we sort out a way to push this down a layer. There is no technical issue; it's just a matter of deciding on an API and adding the requisite tests. We should wait for the next round of databroker internals refactoring before we attempt this.

**Comment by danielballan** [comment]
Superseded by #446
