### ISSUE TITLE
AttributeError in Header.from_run_start

### ISSUE THREAD

**Issue by pavoljuhas** [bluesky/databroker#397]
The `Header.from_run_start` function is documented as taking uid strings, but for such argument it fails with `AttributeError`.  Perhaps it should call `hs.mds.run_start_given_uid` [here](https://github.com/NSLS-II/databroker/blob/171c98543d7a06deee2d8518e54d4709653880b3/databroker/_core.py#L107).

Here is a minimum example that produces the error
```python
class request:
    "mock pytest-request-like object"
    @staticmethod
    def addfinalizer(f):
        return

from databroker.tests.utils import build_sqlite_backed_broker
from databroker._core import Header

db = build_sqlite_backed_broker(request)
# this should fail due to invalid uid, but throws AttributeError
h = Header.from_run_start(db, 'run-start-uid', None)

```

**Comment by danielballan** [comment]
Hm, sorry we completely missed this one @pavoljuhas. This method of constructing Headers has been removed from v1, so I'm going to close this.
