### ISSUE TITLE
all-digit uids get treated as scan_id by intake client-server

### ISSUE THREAD

**Issue by gwbischof** [bluesky/databroker#431]
This test fails occasionally with:
`KeyError: '86038425'`

The uuid doesn't have any letters in it so databroker thinks its an index and not a partial uuid.

**Comment by gwbischof** [comment]
This only happens if it is run with the server

**Comment by tacaswell** [comment]
Could probably cast to int -> try -> catch failure -> try again as a string?

**Comment by danielballan** [comment]
That's clever, but it could lead to even more confusing failures. What if the user enters

```py
db['1003']
```

and there happens to be a scan with `scan_id=1003`? If the user gives us a string, we have to assume they mean (partial) UUID.

**Comment by gwbischof** [comment]
test_search_for_smoke is the test.

**Comment by danielballan** [comment]
I think the right fix for this is to make sure that the type---`int` scan_id or `str` (partial) uid---survives the client-server interaction upstream in intake. Since intake's payload is msgpack-encoded, the distinction should survive the passage between client and server.

**Comment by danielballan** [comment]
This is resolved on the 2.0.0-dev branch.
