### ISSUE TITLE
Proposed modification to `databroker.restream`

### ISSUE THREAD

**Issue by ericdill** [bluesky/databroker#44]
The `restream` docstring says that it "can be used as a drop-in replacement for the output of the bluesky Run Engine."  Now that is not _strictly_ true.  `restream` will emit the RunStart, followed by the Descriptors, followed by the Events (sorted by time because get_events is sorted by time because the cursor is sorted by time. Is that the right lingo @arkilic ?) followed by the RunStop.  However, if there is more than one Descriptor, it will not be emitted in the same order that the RunEngine emitted it because the RunEngine emitted it right before it was about to save an Event that was different from the previous events. 

Question: Do we care? Also relevant: Do we care right now?

It would not be difficult to match the output of the RunEngine; just sort all documents by document.time (or document.timstamp, I don't remember off the top of my head) and then just emit them in that order.  Probably makes sense to fix this once someone has a use case where it is relevant that the order is something more like:

```
RunStart
Descriptor0
Event0-0
Event0-1
Event0-1
Descriptor1
Event1-0
Event0-2
Event1-1
...
RunStop
```

instead of (currently implemented)

```
RunStart
Descriptor0
Descriptor1
Event0-0
Event0-1
Event0-1
Event1-0
Event0-2
Event1-1
...
RunStop
```

thoughts?

**Comment by danielballan** [comment]
It's a fair point. I can't think of any good reason that a callback should care about receiving a descriptor too early. As you suggest, I'd like to wait until we encounter such a reason before we address this, which would add complexity and (marginally) affect performance.

**Comment by ericdill** [comment]
> I'd like to wait until we encounter such a reason before we address this, which would add complexity 

That is 100% ok with me.

>  (marginally) affect performance

Technically yes, but I'm not convinced that the extra penalty of one if statement per event yielded would be apparent

**Comment by tacaswell** [comment]
I am -0 on emitting documents in strict generation order until we find a use case where this matters.  I _think_ our story is that the event streams are independent so we only need to ensure that you see the descriptor before you see any of it's events.

One place where this might matter is if we have baseline reads that matter.

**Comment by danielballan** [comment]
This is an old one! We now do this basically as @ericdill suggested. Over in https://github.com/bluesky/event-model/issues/98 we are developing a formal specification and validation for "ordered".
