### ISSUE TITLE
Verify that v1 and v2 can load historical data as well as v0 can.

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#507]
This issue is to track the effort to verify that all historical beamline data at NSLS-II can be loaded using the new codepaths in v2 and v1. We will be watching for errors and any serious performance regressions relative to v0.

In at least one case, we know we need to use the "transform" feature to patch up Event Descriptors that erroneously recorded the shape of the data in their Events. There will likely be others.

**Comment by danielballan** [comment]
Loading all of the data ever taken at NSLS-II seems possibly impractical, so I intend to start by loading the data from the last 6 months and then randomly sampling older data. h/t @stuartcampbell for helping me think this through.

**Comment by gwbischof** [comment]
I setup this private repo for these tests: https://github.com/NSLS-II/databroker-nsls2-tests

**Comment by danielballan** [comment]
Update:

After applying some fixes to event-model and databroker related to this effort, we have loaded 500 randomly selected runs from every beamline (from the last 6 months) several times with 100% success comparing unfilled documents from v0, v1, and v2.

We still plan to load _all_ the unfilled data from the last six months, and we plan to get as far as possible testing _filled_ data from beamlines. Early anecdotal tests with filled data make me optimistic that we can handle the problems we find by writing [transforms](https://github.com/NSLS-II/nslsii/pull/78).

**Comment by danielballan** [comment]
We will continue to do more validation between now and the planned rollout of 1.0.0 at NSLS-II, but the success of recent checks (noted in my last comment) means this is no longer a blocker for 1.0.0. There will probably be more fixes to come in the 1.0.x release series, but no anticipated API changes or major internal restructurings needed to addressed them.
