### ISSUE TITLE
Review whether canonical yield EventPage, Event, or a mix.

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#530]
I think the intent is to always return EventPage, but in the course of doing something else I think I observed some Events come out of `run.canonical(...)`.

The motivation for always returning EventPages is to make sure that all v2 consumers can handle large numbers of events efficiently.

**Comment by gwbischof** [comment]
canonical(strict_order=True) yields only events.
canonical(strict_order=False) yields only event_pages.
I'll make strict_order=True also yield event pages.
