### ISSUE TITLE
Regression: missing some keys in 'configuration'

### ISSUE THREAD

**Issue by danielballan** [bluesky/databroker#577]
The descriptor configuration includes an `'fccd'` key in v0:

```py
from databroker.v0 import Broker
db = Broker.named('csx')
h = db['80a34702-67aa-48d1-be9b-06f6bb9bffee']
h.descriptors[0]['configuration']
h.descriptors[0]['configuration']['fccd']
```

but is missing it in v1:

```py
from databroker.v1 import Broker as Broker_v1
db_v1 = Broker_v1.named('csx')
h_v1 = db_v1['80a34702-67aa-48d1-be9b-06f6bb9bffee']
h_v1.descriptors[0]['configuration']  # has some keys
h_v1.descriptors[0]['configuration']['fccd']  # but not 'fccd'
```

One thing that's special about `'fccd'` is that it is "external" so I might look around the code paths related to that.

**Comment by danielballan** [comment]
```py
In [16]: keys_v1 = list(h_v1.descriptors[0]['configuration'])                                                                                                                                 

In [17]: keys_v0 = list(h.descriptors[0]['configuration'])                                                                                                                                    

In [18]: set(keys_v0) - set(keys_v1)                                                                                                                                                          
Out[18]: {'fccd'}

```

**Comment by gwbischof** [comment]
What version of databroker is this?

**Comment by ambarb** [comment]
`1.0.2`  at least that was what I used before asking @danielballan about it when trying out stuff at SDCC

**Comment by danielballan** [comment]
Reproduced on 1.0.5. (latest) as well:

```py
In [1]: from databroker.v1 import Broker as Broker_v1                                                                                                                                         

In [2]: db_v1 = Broker_v1.named('csx')                                                                                                                                                        

In [3]: h_v1 = db_v1['80a34702-67aa-48d1-be9b-06f6bb9bffee']                                                                                                                                  

In [4]: h_v1.descriptors[0]['configuration']['fccd']                                                                                                                                          
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-0897f95e7574> in <module>
----> 1 h_v1.descriptors[0]['configuration']['fccd']

KeyError: 'fccd'

In [5]: import databroker                                                                                                                                                                     

In [6]: databroker.__version__                                                                                                                                                                
Out[6]: '1.0.5'
```

**Comment by gwbischof** [comment]
Could the order of the descriptors be different? And we are comparing different streams?

**Comment by gwbischof** [comment]
I added a test here: https://github.com/NSLS-II/databroker-nsls2-tests/blob/compare_header_descriptors/databroker-nsls2-tests/tests/generic.py#L143

**Comment by gwbischof** [comment]
``    def test_header_descriptors(v0_cat, v1_cat, run, beamline):
        if beamline == 'rsoxs':
            pytest.skip()
        v0 = set(v0_cat[run].descriptors[0]['configuration'])
        v1 = set(v1_cat[run].descriptors[0]['configuration'])
>       assert v0 == v1
E       AssertionError

databroker-nsls2-tests/tests/generic.py:148: AssertionError
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/gbischof/dama/databroker-nsls2-tests/databroker-nsls2-tests/tests/generic.py(148)test_header_descriptors()
-> assert v0 == v1
(Pdb) v1_cat[run].descriptors[0]['name']
'baseline'
(Pdb) v0_cat[run].descriptors[0]['name']
'primary'
(Pdb)

**Comment by gwbischof** [comment]
![image](https://user-images.githubusercontent.com/11858848/84200151-42b04d00-aa74-11ea-9f10-b2537c465f8b.png)

**Comment by gwbischof** [comment]
Confirmed that the descriptor order doesn't match
