### ISSUE TITLE
Error when using run.primary.read()

### ISSUE THREAD

**Issue by st3107** [bluesky/databroker#595]
I found that there was always an error when using "run.primary.read()" for the run in `xpd` database on workstation xf28id2.

If I run the following code.

```
In [90]: from databroker import catalog

In [92]: db = catalog['xpd']

In [94]: db[-2]
Out[94]:
BlueskyRun
  uid='334e3aec-6eb4-4166-9a05-4d4be367788e'
  exit_status='success'
  2020-09-02 16:48:38.842 -- 2020-09-02 16:49:39.378
  Streams:
    * primary

In [95]: run = db['334e3aec-6eb4-4166-9a05-4d4be367788e']

In [96]: run.primary.read()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-96-19fb2dd76b7d> in <module>
----> 1 run.primary.read()

/opt/conda_envs/nsls2-analysis-2020-2.0rc7-1-xpdacq/lib/python3.7/site-packages/databroker/core.py in read(self)
   1468         """
   1469         # Implemented just so we can put in a docstring
-> 1470         return super().read()
   1471
   1472     def to_dask(self):

/opt/conda_envs/nsls2-analysis-2020-2.0rc7-1-xpdacq/lib/python3.7/site-packages/databroker/intake_xarray_core/base.py in read(self)
     47         """Return a version of the xarray with all the data in memory"""
     48         self._load_metadata()
---> 49         return self._ds.load()
     50
     51     def read_chunked(self):

/opt/conda_envs/nsls2-analysis-2020-2.0rc7-1-xpdacq/lib/python3.7/site-packages/xarray/core/dataset.py in load(self, **kwargs)
    659
    660             for k, data in zip(lazy_data, evaluated_data):
--> 661                 self.variables[k].data = data
    662
    663         # load everything else sequentially

/opt/conda_envs/nsls2-analysis-2020-2.0rc7-1-xpdacq/lib/python3.7/site-packages/xarray/core/variable.py in data(self, data)
    354         if data.shape != self.shape:
    355             raise ValueError(
--> 356                 f"replacement data must match the Variable's shape. "
    357                 f"replacement data has shape {data.shape}; Variable has shape {self.shape}"
    358             )

ValueError: replacement data must match the Variable's shape. replacement data has shape (1, 1, 2048, 2048); Variable has shape (1, -1, 2048, 2048)
```

The databroker version is

```
packages in environment at /opt/conda_envs/nsls2-analysis-2020-2.0rc7-1-xpdacq:

Name                    Version                   Build  Channel
databroker                1.0.6                      py_0    https://conda.anaconda.org/nsls2forge
databroker-pack           0.3.0                      py_0    https://conda.anaconda.org/nsls2forge
```

**Comment by danielballan** [comment]
Thanks for the clear report @st3107. Just chiming in quickly to say the issue is understood—will reply in detail later this evening.

**Comment by danielballan** [comment]
The metadata about the `shape` of this array is being recorded incorrectly. The old databroker API:

```py
from databroker import Broker
db = Broker.named('xpd')
header = db[-2]
header.data("something")
```

does not actually refer to the `shape` and any point and thus does not notice or care if it is wrong. The new, experimental API that you have used about _does_ refer to the shape. It uses that information to leverage dask and xarray, both of which improve the user experience (or so we have found so far). But as you observed, we have some work left to do to fix the way `shape` is recorded and then repair the historical record.

In the meantime, we have ways of inferring the correct shape without loading the data, even if the record is wrong. The upcoming release of databroker (probably tomorrow, certainly by the end of this week) will improve this inference mechanism and resolve the particular issue that you hit here.

So --- in the short term, please use the stable "v1" interface. In the medium term, I hope you will give this new interface another try, once we get it working properly. Thanks again for the clear report.

**Comment by st3107** [comment]
Got it. Thank you.

PS: I did some further tests. I export the data to msgpack and synchronized to my local computer and ran databroker on the msgpacks. The v2 interface worked well.

**Comment by danielballan** [comment]
Excellent, that's good to hear.
