### ISSUE TITLE
Account for API changes in tzlocal

### ISSUE THREAD

**Issue by tacaswell** [bluesky/databroker#672]
In https://github.com/regebro/tzlocal/pull/92 (and released it tzlocal 3.0) tzlocal changed from return a pytz object to a zoninfo object.  There is a PR to pin the version back (#671 ) but we will need to adopt to this change going forward.

**Comment by regebro** [comment]
It has become obvious to me lately that the tzlocal 3.0 changes was a mistake. The question is how to fix it.
Since you were affected by this, I'd appreaciate any input.

Discussion: https://github.com/regebro/tzlocal/issues/117
