### ISSUE TITLE
Request for ScanID query that uses start_id and end_id

### ISSUE THREAD

**Issue by michael-sutherland** [bluesky/databroker#711]
This requested query would replace a MongoDB query I was using.

## Expected Behavior
Create a ScanIDRange query to specify the start_id and end_id.  This would be similar to running a MongoDB using scan_id >= start_id and scan_id <= end_id.  Or specifically the following in JSON:
{"scan_id": {
  "$gte": start_id,
  "$lte": end_id
}}
I'd prefer the start_id to default to 0 and the end_id to default to returning everything after the start_id.

## Current Behavior
ScanID must have every scan_id specified explicitly.

## Possible Solution
Create new query object that support start_id and end_id.

## Context
This supports creating a GUI for accessing run data through Tiled/Databroker.

## Your Environment
Using Tiled to remotely access blueSkyEvents.

**Comment by michael-sutherland** [comment]
Related to this issue.  If you request too many scan_ids at once using the current interface, you get the following error: "HTTP/1.1 414 Request-URI Too Large".

**Comment by danielballan** [comment]
A sensible request. Thanks @michael-sutherland.

**Comment by danielballan** [comment]
To Michael’s follow-up comment, we should check the string length in the `encode` method and raise a clear error at that point rather than letting the server fail. Perhaps the error message can recommend using `ScanIDRange`.

**Comment by michael-sutherland** [comment]
Isn't the max URI string length a server setting though?  Would the client know the max length accepted?  (This is getting far beyond my knowledge of using HTTP).

**Comment by danielballan** [comment]
Yes, it's a server-side setting. Tiled will typically be behind a load balancer like nginx, and those applications typically apply a limit in the ballpark of 2000 characters to protect against unreasonably large requests that may in effect be DDoS attacks.

I think it makes sense for us to assume, on the client side, that anything above 2000 characters is liable to elicit a server error from some layer somewhere, whether it's one we control directly (Tiled) or one in between that we don't have any visibility into like some lab reverse proxy. I have seen similar issues with the Globus CLI, and it surprised me that their client exposed a server error without giving any suggestion about what I should do instead. ("You are the Globus client! You should know how to form valid requests to the Globus server!")

This came up recently here: https://github.com/bluesky/tiled/blob/54b26842d1926b451ac6ecd45dd94208bde40f24/tiled/client/xarray.py#L567-L572
