### ISSUE TITLE
Chunking

### ISSUE THREAD

**Issue by gwbischof** [bluesky/databroker#827]
Chunking has a major effect on read performance.  For example, a 61GB dataset took over 1 hour to load through the tiled server with the default chunking.  After spending some time optimizing the chunking we were able to load the dataset in 6 minutes.  One issue with the default chunking is that the chunks often span multiple files. This means that multiple files need to be read and joined to get 1 chunk.

It would be nice to improve the default chunking so that the default chunks don't span files, but this may be impossible because `resource` and `datum` documents can refer to multiple files or parts of files.  I'll investigate this a little bit and see if there is anything we can do.

There is currently a mechanism to override the default chunks at collection time.  You can write the `chunk_list` into the descriptor document which describes the shape of all of the chunks. For example: `((3, 3, 3, 1), (3, 3, 3, 1))`.  This can be done by updating the `describe` method of the Ophyd device.  The problem with this mechanism is that we do not know the shape of the data until the collection is completed (for example, a scan could end early), and therefore we cannot know the `chunk_list` at collection time.

So, I propose that we update this mechanism to accept both a `chunk_list` and `chunk_shape`.  Where `chunk_shape` is a tuple that describes the shape of one chunk. For example: `(3, 3, 3, 1)`.  It is not always possible to know the `chunk_shape` ahead of time (a scan could end early, for example).  To address this, it should also support `auto` and `-1` as described in the Dask docs: https://docs.dask.org/en/latest/array-chunks.html#automatic-chunking

One concern with `chunk_shape` is that it may not perfectly partition the data, which will raise an exception. So we may want some extra logic to avoid this.

Using `chunk_shape` addresses this problem for new Bluesky scans.  We may also need to update existing scans. Here is an example of how we can do that: https://github.com/NSLS-II-TES/profile_collection/blob/main/startup/39-export_data.py#L10

**Comment by danielballan** [comment]
I believe the key is `chunks`, not `chunk_list`. (I don't think I've seen `chunk_list` in this codebase, or any other codebase.)

https://github.com/bluesky/databroker/blob/2550bd8c053139b58a9b6d6ea3f4ad0b9c0c48e6/databroker/mongo_normalized.py#L161-L195

Currently, as shown above, we accept `chunks` from the Descriptor document and ultimately pass it to `dask.array.core.normalize_chunks`, which always returns the long tuple-of-tuples-of-ints form.

There is an accidental internal assumption is this code that `chunks` is in the long form. A refactor would allow `chunks` to be either the short tuple-of-ints form, including special values like `-1` and `"auto"`.

I think there is no need to introduce additional key names `chunk_list` or `chunk_shape` to support this.

**Comment by gwbischof** [comment]
Yep, I agree I wasn't suggesting a new key.  I just made up the names `chunk_list` and `chunk_shape` to refer the two different things that can go in the `chunks` field of the descriptor doc.
